[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=7.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tslumen/_version.py"

[tool.black]
line-length = 100
