[pycodestyle]
format = %(path)s:%(row)4d:%(col)4d:%(code).1s:%(text)s (%(code)s)

[pytest]
norecursedirs= .* *.egg* build dist conda.recipe
addopts =
    --junitxml=junit.xml
    --ignore setup.py
    --ignore run_test.py
    --cov-report term-missing
    --tb native
    --strict-markers
    --durations=20
markers =
    serial: execute test serially (to avoid race conditions)
    buildexcluded: mark a test to be excluded from the package build
